name: '$(Build.SourceBranchName)_$(Date:yyyy.MM.dd)$(Rev:.r)'

trigger: none

variables:
  - template: templates/variables.yml

jobs:
- job: Build
  pool:
    vmImage: ${{ variables.vmImage }}
  steps:
  - template: templates/build-steps.yml
- job: Publish
  pool:
    vmImage: ${{ variables.vmImage }}
  steps:
  - template: templates/publish-steps.yml