
variables:
  - template: templates/variables.yml

stages:
- stage: build
  jobs:
  - job: Build
    pool:
      vmImage: ${{ variables.vmImage }}
    steps:
    - template: templates/build-steps.yml

- stage: publish
  jobs:
  - job:
    strategy:
      matrix:
        win10-x64:
          runtime: win10-x64
        win10-x86:
          runtime: win10-x86
        osx-64:
          runtime: osx-x64
        linux-64:
          runtime: linux-64
        linux-arm:
          runtime: linux-arm
        linux-arm64:
          runtime: linux-arm64
    pool:
      vmImage: $(vmImage)
    steps:
      - template: templates/publish-os-steps.yml


# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'github.com_tidusjar'
#     repositoryName: 'tidusjar/Ombi.Releases'
#     action: 'create'
#     target: 'c7fcbb77b58aef1076d635a9ef99e4374abc8672'
#     tagSource: 'userSpecifiedTag'
#     tag: '$(gitTag)'
#     releaseNotesSource: 'inline'
#     releaseNotesInline: '$(ReleaseNotes)'
#     assets: |
#       $(Build.ArtifactStagingDirectory)/*.zip
#       $(Build.ArtifactStagingDirectory)/*.gz
#     isPreRelease: true
#     changeLogCompareToRelease: 'lastNonDraftRelease'
#     changeLogType: 'commitBased'
#   condition: and(succeeded(), eq(variables['PublishToGithub'], 'true'))