version: 4.0.{build}
configuration: Release
os: Visual Studio 2019

environment:
  nodejs_version: "9.8.0"
  typescript_version: "3.0.1"  
  github_auth_token:
    secure: H/7uCrjmWHGJxgN3l9fbhhdVjvvWI8VVF4ZzQqeXuJwAf+PgSNBdxv4SS+rMQ+RH


    
# Do not build on tags (GitHub and BitBucket)
skip_tags: true

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  - cmd: set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\3.0;%path%
  - cmd: tsc -v
build_script:
  - ps: |
      $deployBranches = @{
        # 'feature/v4',
        'develop',
        'master'
      }
      if(env:APPVEYOR_REPO_BRANCH -in $deployBranches) {
        Write-Output "This is a deployment build"
        ./build.ps1 --settings_skipverification=true --target=build
      }
      else 
      {
        Write-Output "This is a not a deployment build"
        ./build.ps1 --settings_skipverification=true --target=build
      }    

skip_commits:
  files:
    - '**/*.md'

after_build:
- cmd: >-
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\windows.zip"
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\osx.tar.gz"  
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\linux.tar.gz"


    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\linux-arm.tar.gz"


    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\windows-32bit.zip"

    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\linux-arm64.tar.gz"
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\src\**\TestResults\Test*.trx))
    

#cache:
#- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
