--- 
after_build: 
  - 
    cmd: |-
        
        appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\windows.zip"
        
        appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\osx.tar.gz"  
        
        appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\linux.tar.gz"
        
        appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\linux-arm.tar.gz"
        
        appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\windows-32bit.zip"
        
        appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.2\linux-arm64.tar.gz"
  - 
    ps: |-
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\src\**\TestResults\Test*.trx))
build_script: 
  - 
    ps: "./build.ps1 --settings_skipverification=true"
configuration: Release
deploy: 
  - 
    auth_token: 
      secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
    draft: true
    provider: GitHub
    release: "Ombi v$(appveyor_build_version)"
    true: 
      branch: master
environment: 
  github_auth_token: 
    secure: H/7uCrjmWHGJxgN3l9fbhhdVjvvWI8VVF4ZzQqeXuJwAf+PgSNBdxv4SS+rMQ+RH
  nodejs_version: "9.8.0"
  sonarrcloudtoken: 
    secure: WGkIog4wuMSx1q5vmSOgIBXMtI/leMpLbZhi9MJnJdBBuDfcv12zwXg3LQwY0WbE
  typescript_version: "3.0.1"
install: 
  - 
    ps: "Install-Product node $env:nodejs_version"
  - 
    cmd: "set path=%programfiles(x86)%\\\\Microsoft SDKs\\TypeScript\\3.0;%path%"
  - 
    cmd: "tsc -v"
os: "Visual Studio 2017"
version: "4.0.{build}"
