version: 2.2.{build}
configuration: Release
<<<<<<< HEAD
os: Visual Studio 2017
environment:
  nodejs_version: "7.8.0"

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
build_script:
  - ps: ./build.ps1 --settings_skipverification=true

test: off
  
after_build:
- cmd: >-
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.0\windows.zip"
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.0\osx.tar.gz"  
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.0\linux.tar.gz"
=======
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '2.2.1'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.2.1'
before_build:
- cmd: appveyor-retry nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a Ombi.zip %APPVEYOR_BUILD_FOLDER%\Ombi.UI\bin\Release\
>>>>>>> origin/master

    appveyor PushArtifact Ombi.zip
    
<<<<<<< HEAD
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp2.0\linux-arm.tar.gz"
    
    

#cache:
#- '%USERPROFILE%\.nuget\packages'
=======
>>>>>>> origin/master
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
<<<<<<< HEAD

=======
- provider: Environment
  name: Microserver
  on:
    branch: dev
>>>>>>> origin/master
