name: ASP.NET Core CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    
    - name: Build Backend
      run: dotnet build src/Ombi.sln --configuration Release
     
     - name: Install Yarn
       uses: nuxt/actions-yarn@master
     
     - name: Build Frontend
       run: yarn --cdw src/Ombi/ build
